services:
  app:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: test
    #   MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
