services:
  app:
    build: backend
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mongo:7.0.11
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
