apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f helm.yml
    kompose.version: 1.34.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f helm.yml
        kompose.version: 1.34.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/camunda-animal-picture-app-default: "true"
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_URI
                  name: app-configmap
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: app-configmap
            - name: CAMUNDA_SAAS_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: CAMUNDA_SAAS_CLIENT_SECRET
                  name: app-configmap
            - name: CAMUNDA_SAAS_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: CAMUNDA_SAAS_CLIENT_ID
                  name: app-configmap
            - name: CAMUNDA_SAAS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  key: CAMUNDA_SAAS_CLUSTER_ID
                  name: app-configmap
            - name: CAMUNDA_SAAS_REGION
              valueFrom:
                configMapKeyRef:
                  key: CAMUNDA_SAAS_REGION
                  name: app-configmap
          image: camunda-app
          name: api
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
