apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: goldleon/camunda-animal-picture-app:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: MONGODB_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: PORT
            - name: CAMUNDA_SAAS_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: CAMUNDA_SAAS_CLIENT_SECRET
            - name: CAMUNDA_SAAS_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: CAMUNDA_SAAS_CLIENT_ID
            - name: CAMUNDA_SAAS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: CAMUNDA_SAAS_CLUSTER_ID
            - name: CAMUNDA_SAAS_REGION
              valueFrom:
                configMapKeyRef:
                  name: app-env
                  key: CAMUNDA_SAAS_REGION
