spring:
  application:
    name: camunda-animal-picture-app
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/camunda}
server:
  port: ${PORT:8080}

logging:
  charset:
    console: UTF-8
  level:
    org:
      springframework: DEBUG
      mongodb: ERROR
    io:
      camunda: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

# camunda:
# client:
#   mode: saas
#   auth:
#     client-id: .mqMXIWiieMcrTGKsBxPWfAB.payFq9j
#     client-secret: K-kvOLvt4E58doinImv20-Kq_ItYbYDSYNVPrI4EsB1XYs.tFJ4EHJhXZK_t12X1
#   cluster-id: ea45f90b-57bc-464a-a7ab-5b4d7c45db76
#   region: bru-2
# camunda:
#   client:
#     mode: saas
#     identity:
#       audience:
#     zeebe:
#       enabled: true
#     tasklist:
#       enabled: true

#     auth:
#       client-id: .mqMXIWiieMcrTGKsBxPWfAB.payFq9j
#       client-secret: K-kvOLvt4E58doinImv20-Kq_ItYbYDSYNVPrI4EsB1XYs.tFJ4EHJhXZK_t12X1
#     cluster-id: ea45f90b-57bc-464a-a7ab-5b4d7c45db76
#     region: bru-2

zeebe:
  client:
    cloud:
      clusterId: ea45f90b-57bc-464a-a7ab-5b4d7c45db76
      clientId: .mqMXIWiieMcrTGKsBxPWfAB.payFq9j
      clientSecret: K-kvOLvt4E58doinImv20-Kq_ItYbYDSYNVPrI4EsB1XYs.tFJ4EHJhXZK_t12X1
      region: bru-2
# authUrl: https://login.cloud.camunda.io/oauth/token
bpmn:
  resourcePath: bpmn/animal-picture-process.bpmn
  resourceName: animal-picture-process-01.bpmn

api:
  rest:
    dog: https://place.dog/200/300
    bear: https://placebear.com/200/300
    cat: test
